export const ADD = "Add";
export const SIZE = "Size";
export const COLOR = "Color";
export const MOVE = "Move";
export const REMOVE = "Remove";
export const FONT_STYLE = "Font Style";
export const EDIT = "Edit";
export const LIBRARY = "Library";
export const UNSPLASH = "Unsplash";

export const SHAPE = "Shape";
export const TEXT = "Text";
export const IMAGE = "Image";
export const GIF = "Gif";
export const ICONS = "Icons";
export const MORE = "More";

export const CIRCLE = "Circle";
export const RECTANGLE = "Rectangle";
export const ELLIPSE = "Ellipse";
export const LINE = "Line";
export const ICON = "icon";
export const STROKE = "Stroke";
export const FILL = "Fill";
export const ICON_FONT = "FontAwesome";
export const ICON_MATERIAL = "MaterialIcons";
export const ICON_IOS = "Ionicons";
export const ICON_MATERIAL_C = "MaterialCommunityIcons";
export const ICON_ENTYPO = "Entypo";
